[package]

name = "uni-boot"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[dependencies]

core = { path = "../rust-libs/core" }
xen = { path = "../libxen", features = [ "with-core" ] }
uni = { path = "../libuni" }
