language: rust
rust:
    - nightly

sudo: false

env:
    - arch=x86_64
    - arch=i686 ASFLAGS='-m32'

os:
    - linux

script:
    - make bin

    # Only test for x86_64 because i686 runtime libraries are missing
    - if [ $arch = "x86_64" ]; then make test; fi
