[package]

name = "uni"
version = "0.0.1"
authors = ["Baptiste Covolato"]
build = "build.rs"

[lib]
name = "uni"
crate-type = [ "lib" ]

[dependencies.core]
git = "https://github.com/bharrisau/rust-libcore.git"

[build-dependencies]
gcc = "0.3"

[[example]]
name = "hello"
build = "build.rs"
path = "examples/hello/main.rs"
