[package]

name = "xen"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[lib]
name = "xen"
crate-type = [ "lib" ]

[features]

with-core = [ "core" ]

[dependencies]

core = { path = "../rust-libs/core", optional = true }
