[package]

name = "uni"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[lib]
name = "uni"
crate-type = [ "lib" ]

[dependencies]

spin = "0.3.1"
alloc_uni = { path = "../liballoc_uni" }
xen = { path = "../libxen" }

[[example]]
name = "hello"
build = "build.rs"
path = "examples/hello/main.rs"
