[package]

name = "uni"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[lib]
name = "uni"
crate-type = [ "lib" ]

[dependencies]
rlibc = "0.1.4"

[dependencies.heap]
path = "../libheap"

[dependencies.xen]
path = "../libxen"

[[example]]
name = "hello"
build = "build.rs"
path = "examples/hello/main.rs"
