[package]

name = "uni"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[lib]
name = "uni"
crate-type = [ "lib" ]

[dependencies]

core = { path = "../rust-libs/core" }
collections = { path = "../rust-libs/collections" }
spin = { path = "../deps/spinlock-rs" }
alloc_uni = { path = "../liballoc_uni" }
xen = { path = "../libxen" }

[[example]]
name = "hello"
build = "build.rs"
path = "examples/hello/main.rs"
