[package]

name = "intrusive"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[features]

test = []

with-core = [ "rust-libcore" ]

[dependencies]

rust-libcore = { version = "*", optional = true }
