[package]
name = "collections"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[features]

[dependencies]

rust-libcore = "*"

alloc = { path = "../alloc" }
rustc_unicode = { path = "../rustc_unicode" }
