[package]

name = "heap"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[features]

default = [ "intrusive" ]
with-core = [ "core", "intrusive/with-core" ]

[dependencies]

intrusive = { path = "../intrusive", optional = true }

core = { path = "../../rust-libs/core", optional = true }
