[package]

name = "heap"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[features]

test = [ "intrusive" ]

with-core = [ "intrusive/with-core", "rust-libcore" ]

[dependencies]

intrusive = { path = "../intrusive", optional = true }

rust-libcore = { version = "*", optional = true }
