[package]

name = "heap"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[features]

with-core = [ "core" ]

[dependencies]

core = { path = "../rust-libs/core", optional = true }
intrusive = { path = "../libintrusive" }
